### ISSUE TITLE
Warping twice?

### ISSUE THREAD

**Issue by robinchm** [johndpope/MegaPortrait-hack#17]
https://github.com/johndpope/MegaPortrait-hack/blob/6540a70b938aab7ec24972240eeb1c64ece960e5/model.py#L1021

Here `w_em_s2c` already includes `w_rt_s2c` (added in WarpGenerator), we have effectively added `w_rt_s2c` twice. Should not really matter since dense network usually can take care of such scaling.

**Comment by johndpope** [comment]
Thanks Robin.  you're right. 
There was so much code flux last week moving parts of logic around to match the paper. 
I also came across this - https://github.com/johndpope/MegaPortrait-hack/issues/15
