### ISSUE TITLE
Impossible G3D architecture

### ISSUE THREAD

**Issue by robinchm** [johndpope/MegaPortrait-hack#18]
![image](https://github.com/johndpope/MegaPortrait-hack/assets/22679145/e1c24cc5-9ff3-4021-ad27-6cef5faf4d80)

Paper's G3D architecture seems to be plainly wrong.

Let's say feature map at the red circle has the shape (B, C, H, W). And `ResBlock3D` does not change its size. At the blue circle we are adding (B, C, H, W) to (B, C, 2H, 2W). Don't know where the issue is.

**Comment by johndpope** [comment]
ok - in progress.

**Comment by robinchm** [comment]
I end up moving the the shortcut in between the resblock3d and downsample. I think this makes more sense and the author just didn't bother to get such detail correctly present.

**Comment by flyingshan** [comment]
> I end up moving the the shortcut in between the resblock3d and downsample. I think this makes more sense and the author just didn't bother to get such detail correctly present.

Hello, may I ask do you have any experimental results about this, or try other structures?

**Comment by robinchm** [comment]
> > I end up moving the the shortcut in between the resblock3d and downsample. I think this makes more sense and the author just didn't bother to get such detail correctly present.
> 
> Hello, may I ask do you have any experimental results about this, or try other structures?

I haven't even figured out the exact implementation of the network, of course no training was attempted.
