### ISSUE TITLE
loss target

### ISSUE THREAD

**Issue by ChenyangWang95** [johndpope/MegaPortrait-hack#27]
Hi, thanks for the impressed work!

I have a question about the loss. why the losses are calculated between source_frame and output_frame.

![image](https://github.com/johndpope/MegaPortrait-hack/assets/82666466/3389c25c-5c4a-4dfd-9b77-75df318bcbe5)

It may be the difference between output_frame and driving_frame?

![image](https://github.com/johndpope/MegaPortrait-hack/assets/82666466/cd69630b-9eab-4cc5-b73b-dbc497834099)

**Comment by johndpope** [comment]
i switch the loss to use driving in this branch - https://github.com/johndpope/MegaPortrait-hack/pull/28

**Comment by johndpope** [comment]
happy to look at a PR 

in mean time - i switch this back because the generator seems to focus on  driving video exclusively - disregarding the source video.
![Screenshot from 2024-06-02 06-55-22](https://github.com/johndpope/MegaPortrait-hack/assets/289994/2ac02777-0170-4c80-884e-f633f3a3fd19)


![Screenshot from 2024-06-02 06-57-01](https://github.com/johndpope/MegaPortrait-hack/assets/289994/9b712990-776c-41c7-bbdd-3af7018a2dbe)

**Comment by ChenyangWang95** [comment]
It seems that the source frame and driving frame are sampled from the same video in the paper.
If I understand correctly, maybe the perceptual and adversarial loss are still calculated between driving_frame and output_frame?

![image](https://github.com/johndpope/MegaPortrait-hack/assets/82666466/343a74a3-63ef-4349-afff-2ac209ae8082)
![image](https://github.com/johndpope/MegaPortrait-hack/assets/82666466/a4acb580-5ee5-4cbf-acf1-59beacd8a35c)

Also, where can I download 512x512 video? I can only get 256x256 voxceleb2.

**Comment by johndpope** [comment]
i overhaul training
https://github.com/johndpope/MegaPortrait-hack/issues/32


https://github.com/johndpope/MegaPortrait-hack/pull/33

30gb torrent here - 
https://academictorrents.com/details/843b5adb0358124d388c4e9836654c246b988ff4

**Comment by ChenyangWang95** [comment]
got it! thx!

**Comment by johndpope** [comment]
@ChenyangWang95 - please check - logic has been updated - and there's a lot preprocessing work to warp and crop - but it's not converging...... 
PR https://github.com/johndpope/MegaPortrait-hack/pull/33

UPDATE - i think I make some progress...
will update in a few hours once i get through some training epochs....

**Comment by johndpope** [comment]
i think i got it. training now. i merged to main.
