### ISSUE TITLE
Are high resolution and student models trainable now?

### ISSUE THREAD

**Issue by vishwaraghava009** [johndpope/MegaPortrait-hack#50]
Hello,
Great progress!
Are high resolution and student models are trainable now?

**Comment by johndpope** [comment]
Thanks for the encourgement.

there is this super resolution model here
https://github.com/Meta-Portrait/MetaPortrait/tree/main/sr_model

my plan is to nail down base model - then switch back to VASA paper. 
https://github.com/johndpope/VASA-1-hack/tree/MegaPortraits


im not happy with base model training - the cross_reenacted_image is going to take 2 years to train on 3090

you can run it and inspect 
the details in this paper on training are dated. 
you can run the main branch - and see results.

i had this idea to just run a crude face swap pass using the source face - with driving video to help stear gradients.
https://github.com/johndpope/MegaPortrait-hack/blob/feat/cheat-loss/train.py#L212 

theres' some id leakage - es is not working properly. 
emoportrait code+ models drops in a few weeks - will render all this work obsolete.

have a look at training details here - https://p0lyfish.github.io/voodoo3d/
they're using evoca.

**Comment by vishwaraghava009** [comment]
Thank you for the swift response

I didn't try training it on a large dataset but when I tried to implement the base model, I faced an out of memory error on my 32GB RAM GPU. 

Your implementation is working fine. I hope the idea, face swap pass, works.

**Comment by johndpope** [comment]
interestingly - https://arxiv.org/pdf/2403.15944
this paper claims to supercede the super resolution model -  metaportrait work by Microsoft.
just got to downgrade the quality to get the model to adapt - https://github.com/Songluchuan/AdaSR-TalkingHead?tab=readme-ov-file
