### ISSUE TITLE
Inter-Reconstructed Feature disentanglement(IRFD) - cheaper / faster / cleaner disentanglement - https://arxiv.org/pdf/2405.07257

### ISSUE THREAD

**Issue by johndpope** [johndpope/MegaPortrait-hack#53]
check it - 
https://arxiv.org/pdf/2405.07257

https://github.com/johndpope/speak-hack

Epoch 0:   0%|▏                                                                                                  | 201/81040 [00:45<5:09:11,  4.36it/s, loss=3.53, step=200]

**Comment by jmanhype** [comment]
let me know how to use need readme 

thanks again !!

**Comment by johndpope** [comment]
after some long days over weekend - i thought i was making progress.
https://github.com/johndpope/SPEAK-hack/pull/3

Unfortunately - it needs rebuilding with GAN / discriminator / generator. 
i attack later - gotta get kids to bed.
