### ISSUE TITLE
README

### ISSUE THREAD

**Issue by tanshuai0219** [johndpope/MegaPortrait-hack#7]
Hi, thanks for your clear open-source codes. Could you write a "README.md" for using these codes?

**Comment by johndpope** [comment]
I'm kinda bricked getting the entire thing to cycle through - 

to be upfront - this worked is predominantly just spat out by Claude Opus
https://github.com/johndpope/MegaPortrait-hack/blob/main/model.py


i ask Claude to align the paper +code - i iterate - sometimes ditch the context and build out the models.
related 
https://github.com/Kevinfringe/MegaPortrait/issues/5

been stuck on just this model and how it should exactly conform to code.
<img width="258" alt="Screenshot 2024-05-16 at 8 30 07 pm" src="https://github.com/johndpope/MegaPortrait-hack/assets/289994/611ddbe5-01d6-41a2-98ce-f9f09dd2a17f">

there's a couple of mp4s in junk folder that should load when you 
**python train.py**

**Comment by johndpope** [comment]
i add some notes - I focus on creating issues that need to get resolved before this will work.
